# Generated by Django 3.0.2 on 2020-01-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('street', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=16)),
                ('owner', models.CharField(max_length=256)),
            ],
        ),
    ]
